### ISSUE TITLE
请问如何搜索关键词

### ISSUE THREAD

**Issue by YYGXjpg** [ultrazg/xyz#1]
readme里面的步骤做完了，怎么搜索关键词得到链接呢？之前没用过go 不太会看，请赐教，感谢~

**Comment by YYGXjpg** [comment]
报错是401 Authorization Required，是需要先登录吗？登录时候的VerifyCode是怎么获取呢?这个APP看起来没有设置密码的地方

**Comment by ultrazg** [comment]
- 401 是因为缺少身份认证信息， 请登录获取 token 信息后再试，除登录接口外所有的接口都需要 token
- 本项目仅支持通过手机验证码登录，请确保手机号已在小宇宙 APP 中注册并使用。参数 `verifyCode` 为手机接收到的验证码
- 项目启动时，会部署一个本地的文档，可以先看看文档再操作

**Comment by ultrazg** [comment]
音频的链接可以在接口返回数据的 media 字段里找到

**Comment by YYGXjpg** [comment]
好的，感谢～我大概知道了。
前面我在Linux上操作，所以没看见文档，现在在PC上弄了，按照文档可以顺利操作了
非常感谢您的贡献！

另，目前看，搜索功能无法跳转到【查看全部】所以只能显示4个节目和一些单集，也无法【按分类】获取节目，想问下近期是否有安排支持呢？

**Comment by ultrazg** [comment]
这个有在更新的计划内，未来的版本将会支持
