### ISSUE TITLE
是否有`更新播放进度`的接口呢？

### ISSUE THREAD

**Issue by rrbe** [ultrazg/xyz#10]
感谢作者贡献这么好的项目

我注意到文档中有提到”单集播放进度“接口，请问是否有”更新播放进度“，以及”将单集加入到待播放列表“相关的接口呢？

顺便问下不知道这个项目的接口都是哪里获取的，是抓包得到的吗？如果需要的话我也可以贡献一下 🤝

**Comment by ultrazg** [comment]
“更新播放进度”得再看看，之前没有留意到这部分，“待播列表”猜测是前端实现的，这两点后续会确认一下。接口基本上是抓包 APP 得到的

**Comment by ultrazg** [comment]
欢迎 PR，如果你熟悉 React，可以加入到该项目的桌面 GUI 开发中来

**Comment by gaojunran** [comment]
@ultrazg 您好，请问您现在是正在开发桌面GUI吗？没看到您仓库中的项目，如果是的话我可以深度参与开发
