### ISSUE TITLE
想问下网页端的用户页面收听时长是不是有问题

### ISSUE THREAD

**Issue by ershouqingge** [ultrazg/xyz#3]
我发现在APP端的收听时长是正常的,抓包发现是通过获取秒数然后转换为小时分钟,需要token

但是我发现网页端的收听时长直接就错的

**Comment by ultrazg** [comment]
网页端指的是从 APP 分享到浏览器打开的那个页面吗？

**Comment by ershouqingge** [comment]
> 网页端指的是从 APP 分享到浏览器打开的那个页面吗？

https://www.xiaoyuzhoufm.com/user/用户id

**Comment by ultrazg** [comment]
测试了几个账号，都存在这个问题，误差在30分钟左右

**Comment by ershouqingge** [comment]
> 测试了几个账号，都存在这个问题，误差在30分钟左右

是的,我搞不懂为什么会有误差....
