### ISSUE TITLE
登录&刷新Token API

### ISSUE THREAD

**Issue by zchengb** [ultrazg/xyz#5]
我看最新的登录API已经是/v1/auth/loginOrSignUpWithSMS了，请问是不是repo的API没对应更新呀？
另外我调/refresh_token是不同的诶，这个API是不是也对应更新了

**Comment by ultrazg** [comment]
这两个接口有什么问题吗？

**Comment by zchengb** [comment]
已通过RSSHub拿到新的API了，感谢 :)
