### ISSUE TITLE
请问要怎么登陆?

### ISSUE THREAD

**Issue by Yirenxs** [ultrazg/xyz#7]
我使用的是win10，下载了 xyz-1.5.2-windows-amd64.exe，双击运行后 窗口弹出：
API 文档：http://localhost:8080/docs
2024/08/10 13:14:48 server start on 8080

我用 http://localhost:8080/docs 是可以打开文档网页的，但我用 http://localhost:8080/login 显示 404 page not found

**Comment by ultrazg** [comment]
这个项目只是提供 api 数据接口，你得要调用它们
